/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.client;

import com.cisco.msx.platform.ApiException;
import com.cisco.msx.platform.model.Error;
import java.util.UUID;
import com.cisco.msx.platform.model.VulnerabilitiesRegistrationPage;
import com.cisco.msx.platform.model.VulnerabilityRegistration;
import com.cisco.msx.platform.model.VulnerabilityRegistrationCreate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegistrationApi
 */
@Ignore
public class RegistrationApiTest {

    private final RegistrationApi api = new RegistrationApi();

    
    /**
     * Delete a registration.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRegisteredProductVersionTest() throws ApiException {
        UUID id = null;
        api.deleteRegisteredProductVersion(id);

        // TODO: test validations
    }
    
    /**
     * Returns a filtered page of registered products / versions.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRegisteredProductVersionPageTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        String product = null;
        String version = null;
        VulnerabilitiesRegistrationPage response = api.getRegisteredProductVersionPage(page, pageSize, product, version);

        // TODO: test validations
    }
    
    /**
     * Register a product / verison combination for vulnerability inspection.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerProductVersionTest() throws ApiException {
        VulnerabilityRegistrationCreate vulnerabilityRegistrationCreate = null;
        VulnerabilityRegistration response = api.registerProductVersion(vulnerabilityRegistrationCreate);

        // TODO: test validations
    }
    
}
