/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.cisco.msx.platform.model.DeviceComplianceState;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DevicePatch
 */
public class DevicePatchTest {
    private final DevicePatch model = new DevicePatch();

    /**
     * Model tests for DevicePatch
     */
    @Test
    public void testDevicePatch() {
        // TODO: test DevicePatch
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'serialKey'
     */
    @Test
    public void serialKeyTest() {
        // TODO: test serialKey
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'complianceState'
     */
    @Test
    public void complianceStateTest() {
        // TODO: test complianceState
    }

}
