/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.cisco.msx.platform.model.DeviceTemplateUpdateDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceTemplateUpdateRequest
 */
public class DeviceTemplateUpdateRequestTest {
    private final DeviceTemplateUpdateRequest model = new DeviceTemplateUpdateRequest();

    /**
     * Model tests for DeviceTemplateUpdateRequest
     */
    @Test
    public void testDeviceTemplateUpdateRequest() {
        // TODO: test DeviceTemplateUpdateRequest
    }

    /**
     * Test the property 'templateDetails'
     */
    @Test
    public void templateDetailsTest() {
        // TODO: test templateDetails
    }

}
