/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LegacySiteDeviceOnboard
 */
public class LegacySiteDeviceOnboardTest {
    private final LegacySiteDeviceOnboard model = new LegacySiteDeviceOnboard();

    /**
     * Model tests for LegacySiteDeviceOnboard
     */
    @Test
    public void testLegacySiteDeviceOnboard() {
        // TODO: test LegacySiteDeviceOnboard
    }

    /**
     * Test the property 'deviceInstanceId'
     */
    @Test
    public void deviceInstanceIdTest() {
        // TODO: test deviceInstanceId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'deviceName'
     */
    @Test
    public void deviceNameTest() {
        // TODO: test deviceName
    }

    /**
     * Test the property 'managed'
     */
    @Test
    public void managedTest() {
        // TODO: test managed
    }

    /**
     * Test the property 'deviceModel'
     */
    @Test
    public void deviceModelTest() {
        // TODO: test deviceModel
    }

    /**
     * Test the property 'deviceOnboardingType'
     */
    @Test
    public void deviceOnboardingTypeTest() {
        // TODO: test deviceOnboardingType
    }

    /**
     * Test the property 'deviceOnboardInformation'
     */
    @Test
    public void deviceOnboardInformationTest() {
        // TODO: test deviceOnboardInformation
    }

}
