/*
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: somecontact@cisco.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.cisco.msx.platform.model.ServiceUILink;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ServiceUIConfig
 */
public class ServiceUIConfigTest {
    private final ServiceUIConfig model = new ServiceUIConfig();

    /**
     * Model tests for ServiceUIConfig
     */
    @Test
    public void testServiceUIConfig() {
        // TODO: test ServiceUIConfig
    }

    /**
     * Test the property 'bannerImage'
     */
    @Test
    public void bannerImageTest() {
        // TODO: test bannerImage
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
