/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TemplateAssignmentResponseAllOf
 */
public class TemplateAssignmentResponseAllOfTest {
    private final TemplateAssignmentResponseAllOf model = new TemplateAssignmentResponseAllOf();

    /**
     * Model tests for TemplateAssignmentResponseAllOf
     */
    @Test
    public void testTemplateAssignmentResponseAllOf() {
        // TODO: test TemplateAssignmentResponseAllOf
    }

    /**
     * Test the property 'responseStatus'
     */
    @Test
    public void responseStatusTest() {
        // TODO: test responseStatus
    }

}
