/*
 * MSX SDK
 * MSX SDK client.
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import com.cisco.msx.platform.model.WorkflowAction;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkflowActionBlock
 */
public class WorkflowActionBlockTest {
    private final WorkflowActionBlock model = new WorkflowActionBlock();

    /**
     * Model tests for WorkflowActionBlock
     */
    @Test
    public void testWorkflowActionBlock() {
        // TODO: test WorkflowActionBlock
    }

    /**
     * Test the property 'uniqueName'
     */
    @Test
    public void uniqueNameTest() {
        // TODO: test uniqueName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'baseType'
     */
    @Test
    public void baseTypeTest() {
        // TODO: test baseType
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'objectType'
     */
    @Test
    public void objectTypeTest() {
        // TODO: test objectType
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'subworkflowId'
     */
    @Test
    public void subworkflowIdTest() {
        // TODO: test subworkflowId
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    public void workflowIdTest() {
        // TODO: test workflowId
    }

    /**
     * Test the property 'schemaId'
     */
    @Test
    public void schemaIdTest() {
        // TODO: test schemaId
    }

}
