/*
 * KAKAPO - MSX SDK
 * MSX Platform SDK
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.msx.platform.model;

import java.util.Objects;
import java.util.Arrays;
import com.cisco.msx.platform.model.DeviceTemplateAccess;
import com.cisco.msx.platform.model.DeviceTemplateAllOf;
import com.cisco.msx.platform.model.DeviceTemplateCreate;
import com.cisco.msx.platform.model.TemplateParameterValidator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * DeviceTemplate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-26T16:01:54.199340-04:00[America/New_York]")
public class DeviceTemplate {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_SERVICE_TYPE = "serviceType";
  @SerializedName(SERIALIZED_NAME_SERVICE_TYPE)
  private String serviceType;

  public static final String SERIALIZED_NAME_DEVICE_MODELS = "deviceModels";
  @SerializedName(SERIALIZED_NAME_DEVICE_MODELS)
  private List<String> deviceModels = null;

  public static final String SERIALIZED_NAME_CONFIG_CONTENT = "configContent";
  @SerializedName(SERIALIZED_NAME_CONFIG_CONTENT)
  private String configContent;

  public static final String SERIALIZED_NAME_RESOURCE_PROVIDER = "resourceProvider";
  @SerializedName(SERIALIZED_NAME_RESOURCE_PROVIDER)
  private String resourceProvider;

  public static final String SERIALIZED_NAME_TEMPLATE_STANDARD = "templateStandard";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_STANDARD)
  private String templateStandard;

  public static final String SERIALIZED_NAME_TENANT_ACCESS = "tenantAccess";
  @SerializedName(SERIALIZED_NAME_TENANT_ACCESS)
  private DeviceTemplateAccess tenantAccess = null;

  public static final String SERIALIZED_NAME_TEMPLATE_PARAMETER_VALIDATORS = "templateParameterValidators";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_PARAMETER_VALIDATORS)
  private List<TemplateParameterValidator> templateParameterValidators = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private UUID userId;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  private OffsetDateTime createdOn;


  public DeviceTemplate name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DeviceTemplate description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public DeviceTemplate version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public DeviceTemplate serviceType(String serviceType) {
    
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @ApiModelProperty(required = true, value = "")

  public String getServiceType() {
    return serviceType;
  }


  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }


  public DeviceTemplate deviceModels(List<String> deviceModels) {
    
    this.deviceModels = deviceModels;
    return this;
  }

  public DeviceTemplate addDeviceModelsItem(String deviceModelsItem) {
    if (this.deviceModels == null) {
      this.deviceModels = new ArrayList<>();
    }
    this.deviceModels.add(deviceModelsItem);
    return this;
  }

   /**
   * Get deviceModels
   * @return deviceModels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDeviceModels() {
    return deviceModels;
  }


  public void setDeviceModels(List<String> deviceModels) {
    this.deviceModels = deviceModels;
  }


  public DeviceTemplate configContent(String configContent) {
    
    this.configContent = configContent;
    return this;
  }

   /**
   * Get configContent
   * @return configContent
  **/
  @ApiModelProperty(required = true, value = "")

  public String getConfigContent() {
    return configContent;
  }


  public void setConfigContent(String configContent) {
    this.configContent = configContent;
  }


  public DeviceTemplate resourceProvider(String resourceProvider) {
    
    this.resourceProvider = resourceProvider;
    return this;
  }

   /**
   * Get resourceProvider
   * @return resourceProvider
  **/
  @ApiModelProperty(required = true, value = "")

  public String getResourceProvider() {
    return resourceProvider;
  }


  public void setResourceProvider(String resourceProvider) {
    this.resourceProvider = resourceProvider;
  }


  public DeviceTemplate templateStandard(String templateStandard) {
    
    this.templateStandard = templateStandard;
    return this;
  }

   /**
   * Get templateStandard
   * @return templateStandard
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTemplateStandard() {
    return templateStandard;
  }


  public void setTemplateStandard(String templateStandard) {
    this.templateStandard = templateStandard;
  }


  public DeviceTemplate tenantAccess(DeviceTemplateAccess tenantAccess) {
    
    this.tenantAccess = tenantAccess;
    return this;
  }

   /**
   * Get tenantAccess
   * @return tenantAccess
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceTemplateAccess getTenantAccess() {
    return tenantAccess;
  }


  public void setTenantAccess(DeviceTemplateAccess tenantAccess) {
    this.tenantAccess = tenantAccess;
  }


  public DeviceTemplate templateParameterValidators(List<TemplateParameterValidator> templateParameterValidators) {
    
    this.templateParameterValidators = templateParameterValidators;
    return this;
  }

  public DeviceTemplate addTemplateParameterValidatorsItem(TemplateParameterValidator templateParameterValidatorsItem) {
    if (this.templateParameterValidators == null) {
      this.templateParameterValidators = new ArrayList<>();
    }
    this.templateParameterValidators.add(templateParameterValidatorsItem);
    return this;
  }

   /**
   * Get templateParameterValidators
   * @return templateParameterValidators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TemplateParameterValidator> getTemplateParameterValidators() {
    return templateParameterValidators;
  }


  public void setTemplateParameterValidators(List<TemplateParameterValidator> templateParameterValidators) {
    this.templateParameterValidators = templateParameterValidators;
  }


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getId() {
    return id;
  }




   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getUserId() {
    return userId;
  }




   /**
   * Get createdOn
   * @return createdOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceTemplate deviceTemplate = (DeviceTemplate) o;
    return Objects.equals(this.name, deviceTemplate.name) &&
        Objects.equals(this.description, deviceTemplate.description) &&
        Objects.equals(this.version, deviceTemplate.version) &&
        Objects.equals(this.serviceType, deviceTemplate.serviceType) &&
        Objects.equals(this.deviceModels, deviceTemplate.deviceModels) &&
        Objects.equals(this.configContent, deviceTemplate.configContent) &&
        Objects.equals(this.resourceProvider, deviceTemplate.resourceProvider) &&
        Objects.equals(this.templateStandard, deviceTemplate.templateStandard) &&
        Objects.equals(this.tenantAccess, deviceTemplate.tenantAccess) &&
        Objects.equals(this.templateParameterValidators, deviceTemplate.templateParameterValidators) &&
        Objects.equals(this.id, deviceTemplate.id) &&
        Objects.equals(this.userId, deviceTemplate.userId) &&
        Objects.equals(this.createdOn, deviceTemplate.createdOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, version, serviceType, deviceModels, configContent, resourceProvider, templateStandard, tenantAccess, templateParameterValidators, id, userId, createdOn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceTemplate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    deviceModels: ").append(toIndentedString(deviceModels)).append("\n");
    sb.append("    configContent: ").append(toIndentedString(configContent)).append("\n");
    sb.append("    resourceProvider: ").append(toIndentedString(resourceProvider)).append("\n");
    sb.append("    templateStandard: ").append(toIndentedString(templateStandard)).append("\n");
    sb.append("    tenantAccess: ").append(toIndentedString(tenantAccess)).append("\n");
    sb.append("    templateParameterValidators: ").append(toIndentedString(templateParameterValidators)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

